name: Automated EXE Compiler

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 pymem Pillow pyinstaller

    - name: Build Standalone EXE with PyInstaller
      run: |
        pyinstaller --clean --onefile --noconsole --uac-admin --icon="cr.ico" --name="SacredWare" --add-data "core;core" --add-data "ui;ui" --add-data "config;config" --add-data "offsets;offsets" --add-data "cr.ico;." main.py

    - name: Upload Binary to Github Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/SacredWare.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "SacredWare Automated Launcher Ready!"
        description: |
          **New Update Released:** ${{ github.ref_name }}
          
          The system has updated the global repositories successfully.
          
          **Instructions:**
          Do not download the raw injector files. Download and run the automated **SacredWare_Installer.exe** launcher below. It will automatically manage folder structures, clean local version caches, and launch the application for you.
          
          [📥 Click here to Download the Setup Installer](https://github.com/TU_USUARIO/SacredWare-Installer/releases/latest/download/SacredWare_Installer.exe)
        color: 0x41cd52
        username: "SacredWare Installer System"
