name: Build SacredWare App
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyInstaller pymem rich colorama PyQt6 Pillow


    - name: Build EXE
      run: |
        pyinstaller --clean --onefile --noconsole --uac-admin --icon="cr.ico" --name="SacredWare" --collect-all PyQt6 --add-data "cr.ico;." --add-data "core;core" --add-data "ui;ui" --add-data "config;config" --add-data "offsets;offsets" main.py

        
    - name: Update Release and Upload EXE
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release edit ${{ github.ref_name }} --repo ${{ github.repository }} 2>/dev/null || \
        gh release create ${{ github.ref_name }} --repo ${{ github.repository }}
        
        gh release upload ${{ github.ref_name }} dist/SacredWare.exe --clobber --repo ${{ github.repository }}
